# Generated by Django 5.1.4 on 2024-12-15 13:43

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_file', models.FileField(help_text="Upload a ZIP file containing your dataset. The ZIP file must contain a single root directory, which includes 'train', 'test', and 'val' folders. <br/><br/>dataset_name.zip/ <br/>└── dataset_name/ <br/>....├── train/ <br/>....├── test/ <br/>....└── val/", upload_to='datasets/', validators=[app.models.validate_zip_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('root_directory', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_file', models.FileField(upload_to='trained_models/', validators=[app.models.validate_keras_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', editable=False, max_length=20)),
                ('base_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='app.trainedmodel')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dataset')),
                ('output_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_from_job', to='app.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='app.trainingjob')),
            ],
        ),
    ]
