# Generated by Django 5.1.4 on 2025-01-01 19:38

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_file', models.FileField(help_text='Upload a ZIP file containing your dataset. The ZIP file must contain a single root directory, which includes folders for each word. <br/><br/>dataset_name.zip/ <br/>└── dataset_name/ <br/>....├── apple/ <br/>....├── hello/ <br/>....└── love/<br/><br/>(this may take a moment to validate)', upload_to='datasets/', validators=[app.models.validate_zip_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('root_directory', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_file', models.FileField(upload_to='models/', validators=[app.models.validate_keras_file])),
                ('max_frames', models.IntegerField(blank=True, null=True)),
                ('num_features', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('words', models.TextField(blank=True, help_text='List of words in the model  (comma separated)', null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('word_accuracy', models.JSONField(blank=True, default=dict, help_text='Word accuracy in the model')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, help_text='Set this model as the one in use')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', editable=False, max_length=20)),
                ('base_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='app.trainedmodel')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dataset')),
                ('output_model', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_from_job', to='app.trainedmodel')),
            ],
        ),
    ]
